### ISSUE TITLE
Viterbi tracking raises ValueError in hmmlearn

### ISSUE THREAD

**Issue by Sleepwalking** [marl/crepe#14]
Hello Maintainers,

Calling `crepe arctic_a0001.wav -V` on the famous ["Author of the danger trail" test sentence](https://github.com/Sleepwalking/libllsm2/blob/master/test/arctic_a0001.wav) from Arctic database resulted in the following error.

This is CREPE 0.0.4 installed from pip.

```
329/329 [==============================] - 7s 20ms/step
Traceback (most recent call last):
  File "/home/sleepwalking/contrib/miniconda2/bin/crepe", line 11, in <module>
    sys.exit(main())
  File "/home/sleepwalking/contrib/miniconda2/lib/python2.7/site-packages/crepe/cli.py", line 115, in main
    args.save_activation, args.save_plot, args.plot_voicing)
  File "/home/sleepwalking/contrib/miniconda2/lib/python2.7/site-packages/crepe/cli.py", line 63, in run
    save_activation, save_plot, plot_voicing)
  File "/home/sleepwalking/contrib/miniconda2/lib/python2.7/site-packages/crepe/core.py", line 252, in process_file
    time, frequency, confidence, activation = predict(audio, sr, viterbi)
  File "/home/sleepwalking/contrib/miniconda2/lib/python2.7/site-packages/crepe/core.py", line 202, in predict
    cents = to_viterbi_cents(activation)
  File "/home/sleepwalking/contrib/miniconda2/lib/python2.7/site-packages/crepe/core.py", line 122, in to_viterbi_cents
    path = model.predict(observations.reshape(-1, 1), [len(observations)])
  File "/home/sleepwalking/contrib/miniconda2/lib/python2.7/site-packages/hmmlearn/base.py", line 334, in predict
    _, state_sequence = self.decode(X, lengths)
  File "/home/sleepwalking/contrib/miniconda2/lib/python2.7/site-packages/hmmlearn/base.py", line 294, in decode
    self._check()
  File "/home/sleepwalking/contrib/miniconda2/lib/python2.7/site-packages/hmmlearn/hmm.py", line 394, in _check
    super(MultinomialHMM, self)._check()
  File "/home/sleepwalking/contrib/miniconda2/lib/python2.7/site-packages/hmmlearn/base.py", line 524, in _check
    .format(self.transmat_.sum(axis=1)))
ValueError: rows of transmat_ must sum to 1.0 (got [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0])
```

**Comment by justinsalamon** [comment]
The error is caused by a dependency, hmmlearn. @Sleepwalking can you paste your output for `conda env export` ?  This will help us investigate the problem. 

In the meanwhile, I'd recommend trying to run crepe in a python 3 environment, I just installed crepe via pip in a python 3.5 conda environment and it worked fine.
