### ISSUE TITLE
SSL Error when installing crepe

### ISSUE THREAD

**Issue by ManishJu** [marl/crepe#95]
```
 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      /private/var/folders/56/8h0vhww154703m1qmty5j0xm0000gp/T/pip-req-build-xj9rjy7a/setup.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
        import imp
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
          h.request(req.get_method(), req.selector, req.data, headers,
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
          self._send_request(method, url, body, headers, encode_chunked)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
          self.endheaders(body, encode_chunked=encode_chunked)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
          self._send_output(message_body, encode_chunked=encode_chunked)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
          self.send(msg)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
          self.connect()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
          self.sock = self._context.wrap_socket(self.sock,
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
          return self.sslsocket_class._create(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
          self.do_handshake()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
          self._sslobj.do_handshake()
      ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/56/8h0vhww154703m1qmty5j0xm0000gp/T/pip-req-build-xj9rjy7a/setup.py", line 30, in <module>
          urlretrieve(base_url + compressed_file, compressed_path)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 241, in urlretrieve
          with contextlib.closing(urlopen(url, data)) as fp:
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
          response = self._open(req, data)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
          result = self._call_chain(self.handle_open, protocol, protocol +
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
          result = func(*args)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
          return self.do_open(http.client.HTTPSConnection, req,
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
          raise URLError(err)
      urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
      Downloading weight file model-tiny.h5.bz2 ...
      [end of output]
```

**Comment by RuinianChen** [comment]
I also met this error

**Comment by yawjalik** [comment]
Also facing the same error here. Are there any solutions yet?

**Comment by yawjalik** [comment]
@yzchen563 Did you by any chance attempt to install crepe on MacOS? I reinstalled python on my machine and there were no more issues.

**Comment by yawjalik** [comment]
@yzchen563 Yes, it's not an issue with the OS, but somehow some ssl certificate configs are kind of weird when installing python on mac. You may have a look at [this post](https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify). 

But I also realized that my python installations are all over the place (some in `/opt/homebrew/bin`, others in `/Applications/Python 3.x`) so I just decided to do a clean installation using homebrew. Everything works fine now, no missing pre-trained models...

**Comment by yawjalik** [comment]
I just did a regular `pip3 install crepe`

**Comment by yawjalik** [comment]
Oh dear.. did you attempt to reinstall python on your machine though? If you haven't and are okay with it, then you may try [this guide](https://apple.stackexchange.com/questions/284824/remove-and-reinstall-python-on-mac-can-i-trust-these-old-references). 

I used vscode to check for all existing python versions that are installed on my machine, uninstalled most of them and reinstalled using homebrew. I also used venv to create my virtual environment when pip installing crepe. Hopefully that will work 🤞

**Comment by dbetchkal** [comment]
Not sure if this will be helpful, but my employer uses SSL encryption, and so every time I use `pip` I have to deliberately include the path to our certificate to avoid these types of errors:
`pip install crepe --cert="T:\Path\To\Certificate\OurRootCA.cer"`

**Comment by debashisbiswas** [comment]
@yzchen563 
> Can you access this address? base_url​&nbsp;​=​&nbsp;​'https://github.com/marl/crepe/raw/models/'

The URL doesn't seem to be the problem. There's nothing at the base URL, but you should be able to access https://github.com/marl/crepe/raw/models/model-tiny.h5.bz2, https://github.com/marl/crepe/raw/models/model-small.h5.bz2, etc

**Comment by JanSchankin** [comment]
Hi together,

I was facing the same issue today on a mac. I was able to solve the problem by refreshing the certificates on my machine using

`/Applications/Python\ 3.12/Install\ Certificates.command` at the bash terminal. If you are using another version of Python you might need to change the path or version number.

However, I believe (not sure though) that this can be fixed in crepe's `setup.py` by changing the rather outdated `urlretrieve` to `requests`, since the latter has a more robust way to deal with certificate chains.
